### ISSUE TITLE
Render the hex string with the fixed-width font

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/www-rlp#4]
![fixed](https://user-images.githubusercontent.com/1138402/56936968-5e3cea80-6b35-11e9-841c-3cbdc4a8e683.jpg)

**Comment by foriequal0** [comment]
I've pushed a commit in https://github.com/CodeChain-io/www-rlp/pull/1/commits/05c32818a064a9405dd226ebec3b800eb817f0a8
I've forgot to deploy after that.
